# Generated by Django 5.0.1 on 2024-03-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tb_user',
        ),
    ]
