# Generated by Django 5.0.1 on 2024-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default=1, max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
